### PR TITLE
Fix seekTo for remote AAC files

### PR DESCRIPTION
**Pull request by AtixD**
I have a problem. SeekTo for remote AAC files doesn't work. 
This PR solve the problem.
Please accept PR. 
Thanks.

### CODE REVIEW

**Comment by florent37** [comment]
yes I merge it :) and push a new version

**Comment by florent37** [comment]
thanks !

**Comment by florent37** [comment]
`2.0.9+1`

**Comment by AtixD** [comment]
Thanks a lot

**Pull request merged**
