### PR TITLE
negative playspeed 

### PR DESCRIPTION
**Pull request by florent37**

### CODE REVIEW

**Comment by florent37** [comment]
works on ios

**Comment by florent37** [comment]
it seems like negative play speed is only supported on ios 
https://github.com/google/ExoPlayer/issues/1208

maybe I can simulate it with some multiple seeks (ugly)

**Comment by ncr9108** [comment]
@florent37 After Upgrading to 1.4.1 Now Play and Pause Function Not Working.. :(

**Comment by ncr9108** [comment]
I am playing one song at a time. Now if I want to pause song it's a pause on seek bar left-hand side text. but it keeps playing music.

If I Fire stop Command it stops on the spot.

**Comment by florent37** [comment]
Ok I'll fix it tomorrow. You're on iOS ?

**Comment by ncr9108** [comment]
No in Android.

**Comment by florent37** [comment]
Ok thanks :)

**Comment by ncr9108** [comment]
is that problem solved?

**Comment by ncr9108** [comment]
is any progress?

**Comment by florent37** [comment]
not for now I did not have time to work on it, I'll do this today

**Comment by ncr9108** [comment]
Ok :) .if possible do early as I have to deliver a project today :(

**Comment by florent37** [comment]
I'll do my possible...

**Comment by florent37** [comment]
I need to separate play speed & forward rewind, it's not the same thing

**Comment by ncr9108** [comment]
I Forward Rewind With

For Rewind:-  Duration duration = Duration(seconds: 10);
                                _assetsAudioPlayer
                                    .seek(currentPosition - duration);

For Forward:-  Duration duration = Duration(seconds: 10);
                                _assetsAudioPlayer
                                    .seek(currentPosition + duration); 

Play Speed Working Perfectly in 1.4.1

The only issue is Play, Pause, Playpause not working.

**Comment by ncr9108** [comment]
How i resolve that.. because without that no meaning of audio player :(

**Comment by florent37** [comment]
I will push a 1.4.2, with thoses methods : 

```
seek(to)
seekBy(duration) 

setPlaySpeed(speed) //only positive

fowardRewind(speed) //positive : forward, negative, rewind
```

can you try ?

**Comment by ncr9108** [comment]
Sure. I Will try and review soon

**Comment by ncr9108** [comment]
Hey. in 1.4.2 still play and pause not working :(

**Comment by florent37** [comment]
I tried pkay/pause, can you send mea sample code ? 

did you tried the sample ? the main.dart ?

**Comment by ncr9108** [comment]
[MediaPlayer.zip](https://github.com/florent37/Flutter-AssetsAudioPlayer/files/4603647/MediaPlayer.zip)

This is my code.
Yes Tried main.dart
still not working in my app :(

**Comment by ncr9108** [comment]
did I make a mistake?

**Comment by florent37** [comment]
instead of _assetsAudioPlayer
                                    .seek(currentPosition + X)

try _assetsAudioPlayer.seekBy(X)

**Comment by florent37** [comment]
if you want to rewind using playSpeed (negative), try to change 

_assetsAudioPlayer.setPlaySpeed(v);

to 

_assetsAudioPlayer.forwardOrRewind(v);

**Comment by ncr9108** [comment]
Ok After that.. play pause issue solved?

**Comment by florent37** [comment]
you'r handling play & pause on your statemanager, but you can retrieve it with the _assetsAudioPlayer.isPlaying (it's a stream)

```
setState(() {
                                  if (playing == true) {
                                    _assetsAudioPlayer.playOrPause();
                                    assetType = 'assets/play.png';
                                    playing = false;
                                  } else if (playing == false) {
                                    _assetsAudioPlayer.play();
                                    assetType = 'assets/playpause.png';
                                    playing = true;
                                  }
                                });
```

here I think' you're disync with the real play/pause state

**Comment by florent37** [comment]
```
 StreamBuilder(
    stream: _assetsAudioPlayer.isPlaying,
    initialData: false,
    builder: (context, snapshotPlaying) {
      final isPlaying = snapshotPlaying.data;
      this.playing = isPlaying; //update using this value
      return GestureDetector(
          onTap: () async {
            var loginData = await WebConfig.pauseUrl(currentPosition.toString(), chapterMediaID);
            print(loginData);
            setState(() {
              if (isPlaying == true) { //here use isPlaying
                _assetsAudioPlayer.pause(); //call pause
              } else if (playing == false) {
                _assetsAudioPlayer.play();
              }
            });
          },
          child: Container(
            child: Image.asset(
              isPlaying ? 'assets/playpause.png' : 'assets/play.png', //here you can just use isPlaying
              color: Color(buttonColor),
              height: SizeConfig.safeBlockVertical * 15.3,
            ),
          ),
          
    });
```

**Comment by ncr9108** [comment]
Ok... i am applying and review you soon

**Comment by florent37** [comment]
:) tell me if it works I have some time now to help you ;)

**Comment by florent37** [comment]
and push an update of the lib !

**Comment by ncr9108** [comment]
Same issue. That second of left pause. but audio keeps playing.

**Comment by ncr9108** [comment]
if you want my any desk , team viewer i can give it to you too.

**Comment by florent37** [comment]
send me your updated code :)

**Comment by ncr9108** [comment]
Check this out.
[MediaPlayer.zip](https://github.com/florent37/Flutter-AssetsAudioPlayer/files/4603808/MediaPlayer.zip)

**Comment by florent37** [comment]
I check it !

**Comment by ncr9108** [comment]
Ok, tell me if any issue.

**Comment by florent37** [comment]
it happens when you're open, then play, and finally seek by 10 seconds, after that you don"t have control on play/pause ?

**Comment by ncr9108** [comment]
no i am not even using seek or fast forward or anything.
i just open song and than tap pause but not working.

**Comment by florent37** [comment]
ok, I try your code commenting all classes I can't find, and setting a custom url

**Comment by ncr9108** [comment]
if possible ican give my screen.

**Comment by florent37** [comment]
I reproduce it ! trying to find why now

**Comment by ncr9108** [comment]
Ok... Thanks a ton for this.

**Comment by florent37** [comment]
it is my pleasure to help you :)

**Comment by ncr9108** [comment]
If you need any other code I am here just tell me.

**Comment by florent37** [comment]
I think I found, it happen on the exoplayer onPlayerStateChanged, i'm on it

**Comment by florent37** [comment]
yes ! I push a 1.4.2+1 for you, 

I was trying  this code 
[main.dart.zip](https://github.com/florent37/Flutter-AssetsAudioPlayer/files/4603888/main.dart.zip)

**Comment by ncr9108** [comment]
Ok Let me check and review you soon

**Comment by florent37** [comment]
just, can you update this code 

```
_assetsAudioPlayer.open(
            Audio.network(nextSOng),
          );
          _assetsAudioPlayer.seek(parseDuration(lastPlayedDuration));
```

to this code
```
 _assetsAudioPlayer.open(
            Audio.network(nextSOng),
            seek: parseDuration(lastPlayedDuration)
          );
```

giving seek on open ensure it seek when the media loaded

**Comment by ncr9108** [comment]
ok Sure

**Comment by florent37** [comment]
i'm uploading 1.4.2+1

**Comment by florent37** [comment]
done, try please :)

**Comment by ncr9108** [comment]
Okk Checking and review

**Comment by florent37** [comment]
btw thanks for your issues, I added a lot of feature with that !

**Comment by ncr9108** [comment]
Work Like a Charm Man. :) 

Thanks a Lot.

Can I buy you a coffee? ;)

**Comment by florent37** [comment]
i have a ko-fi if you want :)

**Comment by florent37** [comment]
https://ko-fi.com/A160LCC

**Comment by ncr9108** [comment]
For Sure Soon. 

Stay Safe. as i can see a lot cases in france.

**Comment by florent37** [comment]
& don't hesitate to send some issues :) 
I did not have some time because my little baby was born 2 days ago :D but he's sleeping so I can code between two feeds

**Comment by ncr9108** [comment]
Congratulations buddy. :)

For Sure.

**Comment by ncr9108** [comment]
Hey. The app is live ..my client liked it.
I want to ask one question out of the topic.
is there any method or library to call API in the background at every day at 00:00 A.M.

Because I have to fetch data at every new day. I tried the workmanager library but not work properly.

**Comment by ncr9108** [comment]
Sorry For this. actually, in my circle of developers no one working on flutter. so I have to google only.

**Comment by florent37** [comment]
in android you can use (in native) https://developer.android.com/reference/android/app/AlarmManager

**Comment by florent37** [comment]
I don't know it there's a flutter portage :/

**Comment by florent37** [comment]
https://pub.dev/packages/android_alarm_manager

**Comment by ncr9108** [comment]
Ok Thanks.

**Comment by ncr9108** [comment]
Hello.. How Are You ...can we done like this ? when we playing song
Untitled

**Comment by florent37** [comment]
Can you open a new issue for that please ?

**Comment by florent37** [comment]
Maybe you can try to fork https://pub.dev/packages/flutter_visualizers

But I will not add this directly in assets audio player, it make no real sense, it's a plug-in of the plug-in :)

**Comment by florent37** [comment]
“Easy Visualizer with ExoPlayer” de Subash Aryc https://link.medium.com/8PuNKR8MB6

This can help you too (only Android)

**Comment by florent37** [comment]
And on ios it seems more difficult, it's with MYAudioTapProcessor.m

**Comment by ncr9108** [comment]
Okay...Thanks

**Comment by florent37** [comment]
Btw as it's a free open source project, if you want to add it as your own feel free to fork it, implement it then push a pull Request to contribute 🥰

**Comment by ncr9108** [comment]
**Asset Audio Player** not support .m4a file?

**Comment by ncr9108** [comment]
can we add a feature like play song in offline too?

**Pull request merged**
