### PR TITLE
upgrade to latest rxdart, rework platform asset loading to follow docs

### PR DESCRIPTION
**Pull request by dustin-graham**
I needed this to upgrade to the latest RxDart. There were several other upgrades I either found necessary or thought would be helpful.

asset loading update follows:
https://flutter.dev/docs/development/ui/assets-and-images

migrate example to androidx, rebuild ios pods to latest format

simplify audio asset arguments to platform to take advantage of built-in asset lookup API

bumped version

### CODE REVIEW

**Comment by dustin-graham** [comment]
@florent37 please review ^

**Comment by florent37** [comment]
thanks I'm currently checking it and will merge with others fixes :)

**Comment by dustin-graham** [comment]
@florent37 on that last commit you added, you removed the lines that lookup the asset using the flutter-provided lookup API. Was that intentional? The docs indicate that we should use the lookup tool they provide to locate the asset rather than us specifying the location path ourselves.

**Comment by florent37** [comment]
Yes it's a missclick sorry

I fixed it later manually in next commits and tested it.

I also fixed it in Android

Then tried it

And published a 1.0.2 ✌️

Thanks you so much for your work

Le dim. 16 févr. 2020 à 16:31, Dustin Graham <notifications@github.com> a
écrit :

**Comment by robertoltrocha** [comment]
Hi,
is it possible to upgrade  to latest rxdart 0.25.0?
thanks

**Pull request merged**
