### PR TITLE
add custom icon from notification setting

### PR DESCRIPTION
**Pull request by Timus23**
icon should be placed in res/drawable as in example file. and if no icon is passed it will show the default icon.

### CODE REVIEW

**Comment by florent37** [comment]
I'm not a huge fan of giving the resources name directly, because Proguard on release, because 
it's not direct referencies, it's referencies by name

**Comment by florent37** [comment]
look at https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/9628b59b112c19394ad5f4f6580e882693485397

I resolved this like Firebase Notif does : reference the icons in AndroidManifest

it's more static but it's more stable, even in release it will work fine

**Comment by florent37** [comment]
but I like your implementation, maybe we can have a merge of those and add into the README how to keep drawables on R8/Proguard for release

**Comment by Timus23** [comment]
i didn't knew about that. i just thought giving resources name flutter and directly keeping it in drawable is more easier than to use manifest file.

**Comment by florent37** [comment]
yes it's easier, but if we do that, we just have to warn users to protect it from proguard

**Comment by florent37** [comment]
in fact you just have to create a resource file that refer all drawables

like this 

https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/resource-shrinking

part `Keeping Resources` 

```
<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@layout/l_used*_c,@layout/l_used_a,@layout/l_used_b*"/>
```

**Comment by florent37** [comment]
so yes merge your work with mine, then we'll tell this warn in the readme

**Comment by Timus23** [comment]
@florent37 i have merged with the master branch and if icon is given from setting it checks for that and if not it checks for manifest and if it find none than it returns the default icon.

**Comment by florent37** [comment]
thanks a lot for this, I merge it :) will just add some thinkg to prevent user there's not images from assets

**Comment by florent37** [comment]
look at https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/23ef4c6c73b6727e3af9f1e924b52558ce86d569

I also added AndroidResDrawable, which is just here to tell there's not assets images

**Comment by florent37** [comment]
I published it in 2.0.3+4
thanks for you work :)

**Pull request merged**
