### PR TITLE
stop on call

### PR DESCRIPTION
**Pull request by florent37**
implemented using auto focus, need to try it

### CODE REVIEW

**Comment by florent37** [comment]
seems to work :)

**Comment by ekremaksoy47** [comment]
Hello, 
i tried and i tested. when someone calling the sound goes to pause but in the background the audio job is still working and counting seconds.  
Did i do something wrong or you update your codes like this :) ?
p.s : (flutter: ">=1.12.13+hotfix.6 <2.0.0" i do this also in pubspec.yaml file.)

**Comment by florent37** [comment]
"still working and counting seconds" -> what happens for you ? 

you mean if the current music position was at 1:05 when the call happen, it continues to 1:06, 1:07, etc ?

**Comment by florent37** [comment]
I reproduce it, sorry, i'm on it

**Comment by florent37** [comment]
just fixed it and tested it on emulator
you can find the code on `1.4.3+2`

can you try ?

**Comment by ekremaksoy47** [comment]
I will try right now..You are so fast, thank you :)

**Comment by ekremaksoy47** [comment]
Ok, It is working right now :) This is exactly what it has to be. Thanks a alot.

**Comment by florent37** [comment]
Thanks for the issue :)

**Comment by ekremaksoy47** [comment]
Hello,  we have a problem for the last update. It is working for phone calling but when i open another app like youtube or default music player the App stop working (Crushes) and i cant rework it again :( Can you check it please?

**Comment by florent37** [comment]
Ok I look can you open a new issue please ?

**Comment by ekremaksoy47** [comment]
Yes of course

**Pull request merged**
