### PR TITLE
foward rewind

### PR DESCRIPTION
**Pull request by florent37**

### CODE REVIEW

**Comment by ncr9108** [comment]
@florent37 no this thing i already done in my app. rewind 10 seconds . and forward 10 seconds.

I want Feature Like Audio can play in fastforward ....so song can play faster.. or we can slow the song speed. like 2x faster , 4x faster , or 2x slower .. 

Actually my audio is like prayers for kids.. so if they want to faster the prayer..or slower the [rayer they can. that's my concept.

**Comment by florent37** [comment]
Oh you mean a play speed ?

**Comment by florent37** [comment]
I'll look how I can do this on Android & ios.

I thinks I'll need to update the ''rate'' of media players

**Comment by ncr9108** [comment]
Yes Exactly. Play Speed.

**Comment by ncr9108** [comment]
@florent37 How Much time it takes?

**Comment by florent37** [comment]
I'll make it today !

**Comment by florent37** [comment]
I just become a father yesterday 👶 did not have time to be on computer 😅

**Comment by florent37** [comment]
I merge this one (forward / rewind) and open a nw pull request with the play speed :)

**Comment by florent37** [comment]
opened here : https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/67

**Comment by florent37** [comment]
you can try the 1.4.1 👍

**Comment by florent37** [comment]
note that playSpeed is only a positive value

**Comment by florent37** [comment]
I'll add negative rate soon (https://developer.apple.com/documentation/avfoundation/avplayer/1388846-rate)

**Pull request merged**
