### PR TITLE
Fixed: "Unresolved reference: drawable" & "JVM-target compatibility"

### PR DESCRIPTION
**Pull request by Rupakpoddar**

### CODE REVIEW

**Comment by darshanvachhani08** [comment]
@florent37 please merge this PR. it has many fixes for the android jvm issue.

**Comment by darshanvachhani08** [comment]
@florent37 I’d like to kindly request a new release of this package. I’m sure it would be super helpful for all the users out there.

**Comment by vasilich6107** [comment]
Hi @florent37 
Could you release

**Comment by ksokolovskyi** [comment]
@Rupakpoddar could you please explain why `assets_audio_player_web` was removed?
CC @florent37

**Comment by Rupakpoddar** [comment]
Hi @ksokolovskyi! I originally fixed an issue in assets_audio_player for personal use, but after doing so, Android Studio began throwing errors related to the bundled assets_audio_player_web package—even though my app wasn’t configured for web. I couldn’t find a clear reason for the errors, and since I wasn’t targeting web, I removed the web package to move forward.

I later noticed others facing the same issue, so I shared my fork as a temporary workaround (not supporting web) in the issues section. After multiple requests, I opened a pull request with the changes.

Hope that clears things up!

**Pull request merged**
