### PR TITLE
Fixed music not auto changing in playlist

### LINKED ISSUE #519: [question] Does not jump to next Audio in Playlist after completion
THIS DIDN'T HAPPEN BEFORE UPDATING LIBRARY TO NULL SAFETY. I DIDN'T CHANGE ANY OF MY CODE & THIS STARTED HAPPENING.

**Flutter Version**

Latest

My version : 

Latest

Platform : 

Android

**Describe the bug**

The audio player does not jump to next audio in the playlist, regardless of the fact that I've defined `LoopMode.playlist`.

More information: Manually calling `next` makes audio player jump to next audio in the playlist. The only fault is that it does not happen after completion of playback (like it was in earlier version). 

**Small code to reproduce**

This is a simple `play` method that I'm using to play a a list of `Track` (a simple data class).

```dart
abstract class Playback {

  static Future<void> play({required int index, required List<Track> tracks}) async {
    List<Track> _tracks = tracks;
    if (_tracks.length > 20) _tracks = tracks.sublist(index, index + 20);
    List<Audio> audios = <Audio>[];
    _tracks.forEach((Track track) {
      audios.add(
        new Audio.file(
          track.filePath!,
          metas: new Metas(
            id: track.trackId,
            image: new MetasImage.file(
              track.albumArt.path,
            ),
            title: track.trackName!,
            album: track.albumName!,
            artist: track.trackArtistNames!.join(', '),
            extra: track.toMap(),
          )
        ),
      );
    });
    audioPlayer.open(
      new Playlist(
        audios: audios,
        startIndex: index,
      ),
      loopMode: LoopMode.playlist,
      playInBackground: PlayInBackground.enabled,
      headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplug,
      showNotification: true,
      notificationSettings: new NotificationSettings(
        playPauseEnabled: true,
        nextEnabled: true,
        prevEnabled: true,
        seekBarEnabled: true,
        stopEnabled: false,   
      ),
    );
  }
}
```

### PR DESCRIPTION
**Pull request by alexmercerind**
Fixes #519.
Thanks to @jxzy999 for fix.

I'm just opening this pull request.

Let me know if you need changes the other way around. This should work with minimal changes though.

### CODE REVIEW

**Comment by Mayb3Nots** [comment]
Hi @alexmercerind thanks for the pull request. can you confirm this fixes it? It kinda weird because the parameter `isFinished` is not even used in the function.

**Comment by nohli** [comment]
@Mayb3Nots maybe sound null safety doesn't call methods if the argument that comes from a platform channel is null.

This would make sense, since the analyzer can't predict native code behavior.

@alexmercerind great catch! Probably best to remove the parameter altogether, what do you think?

**Comment by alexmercerind** [comment]
@Mayb3Nots,

> Hi @alexmercerind thanks for the pull request. can you confirm this fixes it? It kinda weird because the parameter isFinished is not even used in the function. How does it fix thing can you explain?

Do you really think `isFinished` is needed when the method itself is being called upon completion? 🤦‍♂️

It does not matter if its used or not, its the problem how Android's code is written. That function is only going to be executed upon completion, there was no point of that parameter in the first place, you can either modify the Dart's side to be null or return true or false (whatever you want) from Android. (The iOS version most likely is already returning a bool instead of a null), thus it does not happen. 
```
_recieveChannel.setMethodCallHandler((MethodCall call) async {
      // print('received call ${call.method} with arguments ${call.arguments}');
      switch (call.method) {
        case 'log':
          print('log: ' + call.arguments);
          break;
        case METHOD_FINISHED:
          await _onFinished(call.arguments);
          break;
        case METHOD_NOTIFICATION_NEXT:
          _notificationNext();
          break;
        case METHOD_NOTIFICATION_PREV:
          _notificationPrevious();
          break;
        case METHOD_NOTIFICATION_STOP:
          _notificationStop();
          break;
        case METHOD_NOTIFICATION_PLAY_OR_PAUSE: // eg: from notification
          _notificationPlayPause();
          break;
        case METHOD_ERROR:
          _handleOnError(call.arguments);
          break;
        case METHOD_AUDIO_SESSION_ID:
          if (call.arguments != null) {
            _audioSessionId.add(call.arguments);
          }
          break;
        case METHOD_CURRENT:
          if (call.arguments == null) {
            final current = _current.value;
            if (current != null) {
              final finishedPlay = Playing(
                audio: current.audio,
                index: current.index,
                hasNext: false,
                playlist: current.playlist,
              );
              _playlistAudioFinished.add(finishedPlay);
            }
            _playlistFinished.add(true);
            _current.add(null);
            _playerState.add(PlayerState.stop);
          } else {
            final totalDurationMs =
                _toDuration(call.arguments['totalDurationMs']);

            if (_lastOpenedAssetsAudio != null) {
              final playingAudio = PlayingAudio(
                audio: _lastOpenedAssetsAudio!,
                duration: totalDurationMs,
              );

              if (_playlist != null) {
                final current = Playing(
                  audio: playingAudio,
                  index: _playlist!.playlistIndex,
                  hasNext: _playlist!.hasNext(),
                  playlist: ReadingPlaylist(
                      audios: _playlist!.playlist.audios,
                      currentIndex: _playlist!.playlistIndex,
                      nextIndex: _playlist!.nextIndex(),
                      previousIndex: _playlist!.previousIndex()),
                );
                _current.add(current);
              }
            }
          }
          break;
        case METHOD_POSITION:
          _onPositionReceived(call.arguments);

          break;
        case METHOD_IS_PLAYING:
          final bool playing = call.arguments;
          _isPlaying.add(playing);
          _playerState.add(playing ? PlayerState.play : PlayerState.pause);
          break;
        case METHOD_VOLUME:
          _volume.add(call.arguments);
          break;
        case METHOD_IS_BUFFERING:
          _isBuffering.add(call.arguments);
          break;
        case METHOD_PLAY_SPEED:
          _playSpeed.add(call.arguments);
          break;
        case METHOD_FORWARD_REWIND_SPEED:
          final double newValue = call.arguments;
          if (_forwardRewindSpeed.value != newValue) {
            _forwardRewindSpeed.add(newValue);
          }
          break;
        default:
          print('[ERROR] Channel method ${call.method} not implemented.');
      }
    });
    _registerToAppLifecycle();
  }
```

**Comment by alexmercerind** [comment]
@nohli , this is one of the common issues I also had during migration.

I maintain [dart_vlc](https://github.com/alexmercerind/dart_vlc) and plan to bring windows & linux support to this plugin, I'm a C++ guy & I don't know native android or iOS, so I'm of now use in these mobile OSes.

**Comment by Mayb3Nots** [comment]
I have confirmed that the bug is fixed using this PR. Thanks @nohli @alexmercerind @jxzy999. I just started learning flutter a few months ago and I'm enjoying that journey and open-source software.  I don't know much native code but I would hope to learn and contribute more someday. Cheers!

**Comment by alexmercerind** [comment]
... Alternatively,
you may turn this null to true instead (on Android)
https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/102f1e8515e78a700745f04840da14d23d279b85/android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt#L214-L216

See how iOS implementation already gives true.
https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/102f1e8515e78a700745f04840da14d23d279b85/darwin/Classes/Music.swift#L929-L932

**Comment by Mayb3Nots** [comment]
> ... Alternatively,
> you may turn this null to true instead (on Android)
> https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/102f1e8515e78a700745f04840da14d23d279b85/android/src/main/kotlin/com/github/florent37/assets_audio_player/AssetsAudioPlayerPlugin.kt#L214-L216
> 
> See how iOS implementation already gives true.
> https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/102f1e8515e78a700745f04840da14d23d279b85/darwin/Classes/Music.swift#L929-L932

I am curious why return a value at the first place? Is it required? else why not remove it completely.  Also, @kalismeras61 if you can merge this on your own time it would be great.

**Comment by alexmercerind** [comment]
@Mayb3Nots 

I have said exact same thing above.

> Do you really think isFinished is needed when the method itself is being called upon completion?

**Comment by nohli** [comment]
Thanks for the teamwork! 💯 
Have a great start into the week, guys 👍🏽

**Comment by kalismeras61** [comment]
Hey guys will check it tomorrow and will merge it.

**Review by kalismeras61 — APPROVED** [review]

**Pull request merged**
