### PR TITLE
issue #526 fix 

### PR DESCRIPTION
**Pull request by RR-Reddy**
Empty string assigned if error details are null

### CODE REVIEW

**Comment by Mayb3Nots** [comment]
I think its better to put unknown type/message than to leave it blank. @kalismeras61 could you PR this too? Thanks

**Comment by kalismeras61** [comment]
Merged with added default message.

**Comment by Mayb3Nots** [comment]
@kalismeras61 this doesnt seemed to be merged

**Comment by kalismeras61** [comment]
@Mayb3Nots i did manually working publishing new version.

**Pull request closed without merging**
