### PR TITLE
fix build and package renaming issue

### PR DESCRIPTION
**Pull request by kalismeras61**

### CODE REVIEW

**Comment by nohli** [comment]
@kalismeras61
Can you please publish `3.0.9`, since the [latest version on pub.dev](https://pub.dev/packages/assets_audio_player) doesn't build for Android

```
e: file:///Users/builder/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt:20:49 Unresolved reference: R
e: file:///Users/builder/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt:165:68 Unresolved reference: R
e: file:///Users/builder/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt:169:80 Unresolved reference: R
e: file:///Users/builder/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt:173:81 Unresolved reference: R
e: file:///Users/builder/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt:177:80 Unresolved reference: R
e: file:///Users/builder/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt:181:80 Unresolved reference: R
e: file:///Users/builder/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt:185:80 Unresolved reference: R

FAILURE: Build failed with an exception.
```

**Comment by kalismeras61** [comment]
New version released : assets_audio_player 3.1.0

**Comment by kalismeras61** [comment]
@nohli, i did some improvements and added some new feature for this package in my own repo. When you have time, Can you test it, and let me know. 

Fix for fast click next playing 2 sounds same time
Added fade in / fade out etc...

https://github.com/kalismeras61/assets_audio_player

**Comment by nohli** [comment]
Sure, I will test it. Thanks a lot for maintaining this!
Using this package for the Android side of a production app with ~1.4k DAUs, so always happy for improvements 🙏🏽
Fade out is a great idea - I had implemented it via calling setVolume repeatedly.

**Comment by nohli** [comment]
@kalismeras61 I think you would need to merge the latest plugin changes to your repo 😅

```
The current Dart SDK version is 3.0.6.

Because breathe depends on assets_audio_player from git which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.6.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
```

Also FYI the latest version can crash the app on startup: https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/797.

**Comment by blueeyestw** [comment]
Crashes are still happening even after upgrading to 3.1.0
Looks like it's mainly affecting Pixel, Sony, and Oppo devices for some reason?

image

**Comment by nohli** [comment]
@blueeyestw https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/797

**Comment by blueeyestw** [comment]
> @blueeyestw #797

`Crash on app startup on Google Pixel 6/7 after version 3.0.6`

Does that mean I can temporarily fix the issue by downgrading to version 3.0.5?

**Comment by blueeyestw** [comment]
> > > @blueeyestw #797
> > 
> > 
> > `Crash on app startup on Google Pixel 6/7 after version 3.0.6`
> > Does that mean I can temporarily fix the issue by downgrading to version 3.0.5?
> 
> Which app version was the first time you've seen the crash in Crashlytics, and what plugin version have you used in the version before that one? That's what you could safely downgrade to.
> 
> In my case, version 3.0.6 was safe.

You are right, looking back at my commit history, it looks like crashes started happening after I upgraded from 3.0.6 to 3.1.0

**Comment by blueeyestw** [comment]
Down grading to 3.0.6 doesn't seem to help. My users are still experiencing crashes. It's strange since the crashes only started happening after I upgraded to 3.1.0 but downgrading back to 3.0.6 didn't solve the issue.

**Comment by kalismeras61** [comment]
@blueeyestw Please try version 3.1.1

**Pull request merged**
