### PR TITLE
added notification image place holder when image fetch failed.

### PR DESCRIPTION
**Pull request by Timus23**

### CODE REVIEW

**Comment by florent37** [comment]
for this usecase, it's not mandatory to use a manifest attribute (because it takes a bitmap)

I think it can take another MetaDataImage

for example

```
metas: Metas(
         image: 
                MetasImage.network("https://image...."),
         ),
         onImageFailed: MetasImage.asset("assets/images/myuImage.png"),
)
```

what do you think of this ?

**Comment by Timus23** [comment]
metas need to be passed for each track. i used that bcz we can add there once and it can be common for all failed image. but we can do it like this way also. what do u think??

**Comment by Timus23** [comment]
for separate different place holder for each track that meta approach gonna b better.

**Comment by florent37** [comment]
Yes :)

**Comment by Timus23** [comment]
so should i add method in metas or? is it okey or what to do??

**Comment by florent37** [comment]
Yes please add this field into metas, and if you want I can keep like this and merge, I'll add the code to get h the second meta

**Comment by Timus23** [comment]
okey i will add these into metas and tell you.

**Comment by florent37** [comment]
I will add this :) And keep what you've done

**Comment by Timus23** [comment]
okey thanks a lot :)

**Comment by florent37** [comment]
I did this for you

please look at https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/1da222f0baf8021d7e080b08bd95e892f04f7c23

**Comment by florent37** [comment]
```
private fun displayNotification(action: NotificationAction.Show) {
        GlobalScope.launch(Dispatchers.Main) {
            val image = ImageDownloader.loadBitmap(context = applicationContext, imageMetas = action.audioMetas.image)
            if(image != null){
                displayNotification(action, image) //display without image for now
                return@launch
            }
            val imageOnLoadError = ImageDownloader.loadBitmap(context = applicationContext, imageMetas = action.audioMetas.imageOnLoadError)
            if(imageOnLoadError != null){
                displayNotification(action, imageOnLoadError) //display without image for now
                return@launch
            }

            val imageFromManifest = ImageDownloader.loadHolderBitmapFromManifest(context = applicationContext)
            if(imageFromManifest != null){
                displayNotification(action, imageFromManifest) //display without image for now
                return@launch
            }

            displayNotification(action, null) //display without image
        }
    }
```

**Comment by Timus23** [comment]
okey. thanks a lot :)

**Pull request merged**
