### PR TITLE
stop the player when connection is offline

### PR DESCRIPTION
**Pull request by Timus23**
I have stopped the player when connection status is offline and user try to open the player so it prevent the crash condition and when connection goes offline in the middle of playing online music also it stops the player for now but instead i wanted to pause it. when i pause it and connection become online again it doesnot play again from that position. i didn't figure out why its happening. and also i wanted to add one more enum i.e playerStatus.Error so that we can show appropriate message. Can you help me to achieve this thing ?

### CODE REVIEW

**Comment by florent37** [comment]
thanks, i'll merge this and instead of just stop, I'll ask to flutter what to do in that case, like a callback

```
assetsAudioPlayer.onErrorDo((error, player) {
    player.stop(); 
});
```

or maybe

```
assetsAudioPlayer.open(audio, errorAction: (error, player) {
    player.stop(); 
});
```

**Comment by Timus23** [comment]
> thanks, i'll merge this and instead of just stop, I'll ask to flutter what to do in that case, like a callback
> 
> ```
> assetsAudioPlayer.onErrorDo((error, player) {
>     player.stop(); 
> });
> ```
> 
> or maybe
> 
> ```
> assetsAudioPlayer.open(audio, errorAction: (error, player) {
>     player.stop(); 
> });
> ```

yes it would be better and should be and type of error also. like network error, or any other kind of error. i was thinking how to just pause the player when network goes off any user should be able to continue from that point only without crashing or just stoping the player like utube does.

**Comment by Timus23** [comment]
i tried to handle when exoplayer has already started and phone goes offline. i paused the media player but when if again play the audio it didn't start from that point. even when phone is online.

**Comment by florent37** [comment]
thanks I merge it and will make it evole to apply what I sent to you, the `onError` action from flutter ;)

**Comment by Timus23** [comment]
thank you :)

**Pull request merged**
