### PR TITLE
Migrate to nnbd

### PR DESCRIPTION
**Pull request by nohli**
Closes https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/486

### CODE REVIEW

**Comment by Mayb3Nots** [comment]
Hi @nohli do you need help with migrating the package? I can help if you need any.

**Comment by nohli** [comment]
@Mayb3Nots Packages fluter_audio_recorder and flutter_audio_query (in example app) are not null safe. If you could replace them with different packages, it would help a lot.

**Comment by Mayb3Nots** [comment]
> fluter_audio_recorder

I can try migrate those package to null safety ;)

**Comment by nohli** [comment]
The recorder already has an nnbd PR that you could review (but it only help us if it gets published to pub.dev).

**Comment by Mayb3Nots** [comment]
For now we can use this while waiting for the owners of these packages to update.
flutter_audio_recorder:
  git: 
    url:https://github.com/fayeed/flutter_audio_recorder
    ref: fde3668469b65c059c806c53edd561e9908006ab
As for flutter_audio_query I will migrating the package myself.

**Comment by nohli** [comment]
Yeah. Since it's only the example app and should even be fine. So only the other package - migrating or replacing :)

Also, this package basically consists of three parts - web, example and lib. You can also work on web and/or example if you like? Sent you an invite for collaborating on the migration fork.

**Comment by nohli** [comment]
@kalismeras61 where does the auto-generated library `assets_audio_player_web/lib/generated/i18n.dart` come from?

@Mayb3Nots did you start any migration yet?

**Comment by kalismeras61** [comment]
> @kalismeras61 where do the auto-generated libraries `../lib/generated/i18n.dart` come from? They're not null safe.
> 
> @Mayb3Nots did you start any migration yet?

i don't think it using anywhere, no idea but Florent created this with flutter_i18n package.

**Comment by nohli** [comment]
TODO After assets_audio_player_web is published, the dependency in pubspec.yaml needs to be changed from git to pub.dev in order to publish the main package.

The example app has two git dependencies (of PRs from null safety migration, one from Mayb3Nots 🎉), which should be fine for now.

Also, I declared it as a prerelease and not a stable 3.0.0 version. So much changed code better needs to be tested before making it the next stable.

**Comment by Mayb3Nots** [comment]
> TODO After assets_audio_player_web is published, the dependency in pubspec.yaml needs to be changed from git to pub.dev in order to publish the main package.
> 
> The example app has two git dependencies (of PRs from null safety migration, one from Mayb3Nots 🎉), which should be fine for now.
> 
> Also, I declared it as a prerelease and not a stable 3.0.0 version. So much changed code better needs to be tested before making it the next stable.
> 
> FYI I've added the linter pedantic which further improved some parts of the code. This, and updated dependencies, will result in 20 more pub.dev points.

Thank you so much for your contribution. I am sorry I couldn't be of more use.

**Comment by RR-Reddy** [comment]
can you guys please merge this pull request ASAP and release null safety pre release version. so that people can use this changes in production

cc: @nohli , @kalismeras61

**Comment by nohli** [comment]
@RR-Reddy you can use it in production with

```
  assets_audio_player:
    git:
      url: https://github.com/nohli/Flutter-AssetsAudioPlayer
      ref: migrate-to-nnbd
```

On a side note, if you're not dependent on **sound** null safety right now, the well tested stable release would be safer at the moment.

**Comment by RR-Reddy** [comment]
@nohli  to make it work, we have to override web dependency as below. along with main dependency


```
dependency_overrides:
  assets_audio_player_web:
    git:
      url: https://github.com/nohli/Flutter-AssetsAudioPlayer
      path: assets_audio_player_web
```

**Comment by nohli** [comment]
> @nohli  to make it work, we have to override web dependency as below. along with main dependency
> 
> 
> 
> 
> 
> ```
> 
> dependency_overrides:
> 
>   assets_audio_player_web:
> 
>     git:
> 
>       url: https://github.com/nohli/Flutter-AssetsAudioPlayer
> 
>       path: assets_audio_player_web
> 
> ```

This doesn't look like it's using the nnbd-migrated branch though.

**Comment by nohli** [comment]
@kalismeras61 I've tested the package in my apps and it works well. So far no other reported issues.
In the last days, many packages were upgraded, which (for most users) makes this the only package that needs `dependency_overrides`.

Maybe it can be published to pub.dev (first assets_audio_player_web and then the main package with the updated assets_audio_player_web dependency)?

**Comment by kalismeras61** [comment]
@nohli , thanks for the update. I am going to check my side and will publish new version today.

**Comment by kalismeras61** [comment]
@nohli did you test this for both plaform ? or some did test for android and also ios as well ?

**Comment by nohli** [comment]
@kalismeras61 on both platforms, but let me test the example app on both platforms, too, just to make sure.

**Pull request merged**
